name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: [1.10.3]
        otp: [22.2.8]

    steps:
    - uses: actions/checkout@v2

    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }} # Define the elixir version [required]
        otp-version: ${{ matrix.otp }} # Define the OTP version [required]

    - name: Retrieve Mix Dependencies Cache
      uses: actions/cache@v1
      id: mix-cache #id to use in retrieve action
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - name: Install Mix Dependencies
      env:
        MIX_HEX_KEY: ${{ secrets.HEX_API_KEY }}
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mix hex.organization auth motel --key $MIX_HEX_KEY
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Elixir - Warning-Free Compile
      env:
        MIX_ENV: test
      run: mix compile --warnings-as-errors
    
    - name: Check Formatting
      run: mix format --check-formatted

    - name: Run Credo
      run: mix credo --strict

    - name: Run Tests
      run: mix test